services:
  - type: web
    name: slovak-speech-sim
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
